limites: practica_3/tiempomax.c 
		gcc -Wall -g -std=c99  practica_3/tiempomax.c -o practica_3/tiempomax
factorial: practica_3/tiempomax.c 
		gcc -Wall -g -std=c99  practica_5/factorial.c -o practica_5/factorial
heap: practica_12/static.c 
	gcc -Wall -g -std=c99  practica_12/static.c -o practica_12/static
ofuscando: practica_13/ofuscando.c 
		gcc -Wall -g -std=c99  practica_13/ofuscando.c -o practica_13/ofuscando
aleatorios: practica_14/aleatorios.c 
		gcc -Wall -g -std=c99  practica_14/aleatorios.c -o practica_14/aleatorios
hash: practica_16/md5.c 
		gcc -Wall -g -std=c99  practica_16/md5.c -o practica_16/md5
